import {
    AlertCircle,
    AlertTriangle,
    CheckCircle2,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    Circle,
    Clock,
    Copy,
    Eye,
    EyeOff,
    HelpCircle,
    Info,
    Loader2,
    Lock,
    Moon,
    MoreHorizontal,
    Plus,
    RefreshCw,
    Search,
    Server,
    Settings2,
    Shield,
    Sun,
    Trash2,
    X,
    XCircle,
} from "lucide-react";

/**
 * Common icons used throughout the UI components
 */
export const Icons = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circle: Circle,
  clock: Clock,
  copy: Copy,
  eye: Eye,
  eyeOff: EyeOff,
  helpCircle: HelpCircle,
  info: Info,
  loader: Loader2,
  lock: Lock,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  refreshCw: RefreshCw,
  search: Search,
  server: Server,
  settings: Settings2,
  shield: Shield,
  sun: Sun,
  trash: Trash2,
  x: X,
  xCircle: XCircle,
} as const;

