import {
  AlertCircle,
  AlertTriangle,
  AlertTriangleIcon,
  AppWindow,
  ArrowLeft,
  ArrowRightIcon,
  BarChart3,
  Bell,
  BellIcon,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  Clock,
  ContactRound,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  EditIcon,
  Ellipsis,
  EllipsisVerticalIcon,
  ExternalLink,
  FileArchive,
  FileCode2,
  FileIcon,
  FileSpreadsheet,
  FileText,
  FilterIcon,
  Flag,
  Folder,
  GitBranch,
  GitCommit,
  GitMerge,
  Globe,
  HelpCircleIcon,
  HomeIcon,
  Image,
  ImageIcon,
  Images,
  ImageUp,
  Info,
  InfoIcon,
  Library,
  LibraryBig,
  LibrarySquare,
  List,
  Loader2,
  Lock,
  LockKeyhole,
  LogInIcon,
  LogOutIcon,
  LucidePlusCircle,
  MenuIcon,
  MessageCircleQuestion,
  MessagesSquare,
  MonitorCheck,
  MonitorCog,
  MonitorSmartphone,
  MonitorSpeaker,
  MoonIcon,
  Music,
  Newspaper,
  Palette,
  Plus,
  PlusSquareIcon,
  Podcast,
  ReceiptIcon,
  RefreshCw,
  Rocket,
  Rss,
  Save,
  Search,
  Server,
  Settings2,
  Shield,
  ShieldCheck,
  ShieldEllipsis,
  ShieldPlus,
  SlashIcon,
  Sparkles,
  SquareLibrary,
  SunIcon,
  Trash2Icon,
  User2,
  UserCog,
  UserIcon,
  UserPen,
  Users,
  VideoIcon,
  WandSparkles,
  Wrench,
  XIcon,
  Zap,
} from "lucide-react";
import { BiGitBranch, BiGitCommit } from "react-icons/bi";
import { BsGripVertical } from "react-icons/bs";
import { CiSaveDown2 } from "react-icons/ci";
import { FaAws, FaCode, FaDev, FaGit, FaReact } from "react-icons/fa";
import { FaApple, FaStripe } from "react-icons/fa6";
import { FcGoogle } from "react-icons/fc";
import { HiOutlineSparkles } from "react-icons/hi2";
import { ImGit } from "react-icons/im";
import { IoSparkles, IoSparklesOutline } from "react-icons/io5";
import {
  LuActivity,
  LuArchive,
  LuBolt,
  LuBook,
  LuBuilding,
  LuCalendar,
  LuCheck,
  LuChevronsUpDown,
  LuCircle,
  LuCircleArrowUp,
  LuClock,
  LuCloud,
  LuCreditCard,
  LuCrown,
  LuDatabase,
  LuDollarSign,
  LuEye,
  LuEyeOff,
  LuFile,
  LuFileText,
  LuFolderGit2,
  LuGitFork,
  LuGitPullRequest,
  LuGlobe,
  LuHardDrive,
  LuHash,
  LuHistory,
  LuHouse,
  LuInfo,
  LuKey,
  LuLayers,
  LuLayoutDashboard,
  LuLayoutGrid,
  LuLinkedin,
  LuList,
  LuLoader,
  LuLogIn,
  LuLogOut,
  LuLogs,
  LuMail,
  LuMapPin,
  LuMessageSquare,
  LuMonitor,
  LuMonitorSmartphone,
  LuMousePointer,
  LuNewspaper,
  LuPackage,
  LuPlug,
  LuPlus,
  LuPuzzle,
  LuRocket,
  LuRss,
  LuScrollText,
  LuSearch,
  LuServer,
  LuSettings,
  LuSettings2,
  LuShield,
  LuSmartphone,
  LuSparkles,
  LuSquareCode,
  LuSquarePen,
  LuStar,
  LuTablet,
  LuTrash,
  LuTrash2,
  LuTrendingDown,
  LuTrendingUp,
  LuTwitter,
  LuUnplug,
  LuUpload,
  LuUserCheck,
  LuUserPlus,
  LuUsers,
  LuUsersRound,
  LuUserX,
  LuVariable,
  LuVideo,
  LuWebhook,
  LuX,
  LuYoutube,
} from "react-icons/lu";
import {
  MdOutlineAdminPanelSettings,
  MdOutlineFormatSize,
  MdOutlineTypeSpecimen,
} from "react-icons/md";
import {
  PiDotsSixVerticalBold,
  PiSparkle,
  PiSparkleLight,
  PiStack,
  PiTelegramLogo,
} from "react-icons/pi";
import {
  RiAiGenerate,
  RiAiGenerate2,
  RiGithubFill,
  RiGitlabFill,
  RiSparklingLine,
} from "react-icons/ri";
import { SiBlazor, SiNextdotjs, SiSupabase } from "react-icons/si";
import {
  TbBrandBitbucketFilled,
  TbCloudNetwork,
  TbEditCircle,
  TbGlobe,
  TbLockFilled,
  TbReportMoney,
  TbShieldCheckFilled,
  TbStack2,
  TbUser,
} from "react-icons/tb";
import { VscAzure, VscSparkle } from "react-icons/vsc";

export const Icons = {
  FaApple,
  ExternalLink: ExternalLink,
  AlertTriangle,
  FileText,
  LuKey,
  LuHouse,
  LuRss,
  LuNewspaper,
  LuDollarSign,
  LuBook,
  LuSquarePen,
  LuLogIn,
  LuCrown,
  LuVariable,
  LuScrollText,
  LuMessageSquare,
  LuBuilding,
  LuLayers,
  LuSquareCode,
  LuRocket,
  LuBolt,
  LuTrendingUp,
  LuMousePointer,
  LuActivity,
  LuFolderGit2,
  LuTrendingDown,
  LuPuzzle,
  LuCloud,
  LuCheck,
  LuTrash,
  LuInfo,
  LuHash,
  EyeOff: LuEyeOff,
  GitCommit,
  BiGitCommit,
  AlertCircle,
  GitHub: RiGithubFill,
  GitLab: RiGitlabFill,
  LuYoutube,
  LuLinkedin,
  LuTwitter,
  Bitbucket: TbBrandBitbucketFilled,
  LuPackage,
  Bell,
  AzureDevOps: VscAzure,
  Dashboard: HomeIcon,
  Login: LogInIcon,
  InfoIcon,
  Info,
  Ellipsis,
  ImageUp,
  Globe,
  LuGlobe,
  XIcon,
  CreditCard,
  FilterIcon,
  TbEditCircle,
  MdOutlineFormatSize,
  MdOutlineTypeSpecimen,
  PiDotsSixVerticalBold,
  BsGripVertical,
  Google: FcGoogle,
  Supabase: (props: any) => <SiSupabase color="#3ECF8E" {...props} />,
  Stripe: (props: any) => (
    <FaStripe color="#635BFF" className="size-6" {...props} />
  ),
  AWS: (props: any) => <FaAws color="#FF9900" {...props} />,
  Logout: LogOutIcon,
  ArrowLeft,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronUp: ChevronUpIcon,
  ChevronDown: ChevronDownIcon,
  LuChevronsUpDown,
  Download,
  MessagesSquare: MessagesSquare,
  Folder,
  TbStack2,
  TbReportMoney,
  TbCloudNetwork,
  Projects: BriefcaseBusiness,
  Plus,
  Sparkles,
  WandSparkles,
  IoSparkles,
  PiSparkleLight,
  PiSparkle,
  LuSparkles,
  IoSparklesOutline,
  RiAiGenerate,
  RiAiGenerate2,
  HiOutlineSparkles,
  VscSparkle,
  RiSparklingLine,
  Newspaper,
  Trash: Trash2Icon,
  Page: FileIcon,
  UserPen,
  User2,
  LuUsersRound,
  LuUsers,
  LuList,
  CheckCircle,
  LuSearch,
  LuLayoutGrid,

  LuLogs,
  PiTelegramLogo,
  Settings: Settings2,
  Team: ContactRound,
  BriefcaseBusiness: BriefcaseBusiness,
  Briefcase,
  MessageCircleQuestion,
  Search: Search,
  Shield: Shield,
  LuShield,
  LuCalendar,
  LuTrash2,
  UserCog,
  ShieldUser: ShieldPlus,
  ShieldEllipsis: ShieldEllipsis,
  ShieldCheck,
  Images,
  Image,
  SquareLibrary,
  Library,
  Lock,
  LockKeyhole,
  TbLockFilled,
  LibraryBig,
  LibrarySquare,
  Billing: ReceiptIcon,
  Menu: MenuIcon,
  Media: MenuIcon,
  FaGit,
  ImGit,
  Add: PlusSquareIcon,
  Slash: SlashIcon,
  LuSettings,
  LuMail,
  Mail: LuMail,
  Flag,
  MonitorCog,
  MonitorSpeaker,
  Edit: EditIcon,
  Warning: AlertTriangleIcon,
  User: UserIcon,
  Wrench,
  Palette,
  AppWindow,
  ArrowRight: ArrowRightIcon,
  Support: HelpCircleIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  MonitorSmartphone: MonitorSmartphone,
  DotsVertical: EllipsisVerticalIcon,
  Bells: BellIcon,
  Users: Users,
  LuSettings2,
  LuServer,
  MdOutlineAdminPanelSettings,
  LuLayoutDashboard,
  LuDatabase,
  LuUnplug,
  TbGlobe,
  Podcast: Podcast,
  Rss: Rss,
  Save,
  CiSaveDown2,
  TbShieldCheckFilled,
  Check,
  LuCircleArrowUp,
  CheckCircle2,
  MonitorCheck,
  Calendar,
  LuHardDrive,
  PiStack,
  Clock,
  RefreshCw,
  Copy,
  Building2,
  Spinner: Loader2,
  X: XIcon,
  HelpCircle: HelpCircleIcon,
  Zap,
  FolderOpen: Folder,
  Rocket,
  LuLoader,
  Loader2,
  GitBranch,
  BiGitBranch,
  GitMerge,
  BarChart3,
  List,

  Eye: LuEye,
  LuWebhook,
  LuPlug,
  LuGitFork,
  LuGitPullRequest,
  LuStar,
  LuUserX,
  LuUserPlus,
  LuUserCheck,
  TbUser,
  LuX,
  LuMonitorSmartphone,
  LuSmartphone,
  LuTablet,
  LuMonitor,
  LuLogOut,
  LuMapPin,
  LuClock,
  LuPlus,
  LuUpload,
  LuVideo,
  LuFileText,
  LuArchive,
  LuFile,
  LucidePlusCircle,
  LuCircle,
  Brain,
  Cpu,
  Database,
  Server,
  Subscription: LuCreditCard,
  History: LuHistory,
  FaCode,
  FaDev,
  FaReact,
  SiBlazor,
  SiNextdotjs,
};
export type IconName = keyof typeof Icons;
export type IconComponent = (typeof Icons)[IconName]; // the actual icon component type

export const getFileIcon = (mimeType: string | undefined) => {
  if (!mimeType) return FileText;

  if (mimeType.startsWith("image")) return ImageIcon;
  if (mimeType.startsWith("audio")) return Music;
  if (mimeType.startsWith("video")) return VideoIcon;
  if (mimeType === "application/pdf") return LuFile;
  if (
    mimeType === "application/zip" ||
    mimeType === "application/x-zip-compressed"
  )
    return FileArchive;
  if (mimeType.startsWith("text") || mimeType === "application/json")
    return FileCode2;
  if (mimeType.includes("spreadsheet") || mimeType.includes("excel"))
    return FileSpreadsheet;
  if (mimeType.includes("word")) return LuFileText;

  return FileText; // default fallback
};
